### ISSUE TITLE
forwarding the midi signal from usb midi to loopbe midi results in keys staying in pushed position in DAW

### ISSUE THREAD

**Issue by cer093** [brianops1/OSCMidi#1]
Hey brianops1, I'm experiencing issues using your script. when using my pianos usb midi input as an input device and the LoopBe internal midi, it does pick up the keys being played. however, using a DAW (I'm using Synthesia) to display the results it recognizes the keys being played but not the keys being lifted again. as a consequence, the keys are being pushed down and never lift back. this results in the avatars keys also being pushed down forever, if played once. 

I've tried troubleshooting everything i can on my end including reinstalling the software meantioned in the readme file.
do you have an idea, what the issue could be?

thank you!

**Comment by brianops1** [comment]
"it recognizes the keys being played but not the keys being lifted again" I believe this is an issue with the way the program parses notes. So when using Synthesia, I assume you are only inputting LoopBe and not outputting anything else. And then in the OSC Midi program, you are inputting your piano and outputting to LoopBe. If that is the case then I'm not entirely sure why it wouldn't be lifting. 

Something to try: when in the program, if you activate the debug mode and hit & hold a key, then wait a second, then release, and then post what comes up in the console, that will give me a better idea of what type of inputs your piano is outputting into the program. And if you could explain how the program works otherwise, like does the keys to the avatar work?

Also, if you are not inputting your piano into the OSC Midi program and outputting to loopbe through Synthesia, this is fine but do the same debug test as synthesia might be outputting something weird? I'm not sure.

**Comment by cer093** [comment]
Thank you for your response!

"So when using Synthesia, I assume you are only inputting LoopBe and not outputting anything else. And then in the OSC Midi program, you are inputting your piano and outputting to LoopBe. And then in the OSC Midi program, you are inputting your piano and outputting to LoopBe." 

Correct. The only input in Synthesia is LoopBe and there is no output. The input in OSC Midi is set to be b'USB-MIDI' which is the midi input from my piano. The output is set to b'LoopBe Internal MIDI'. Port Style 1. Every other toggle is set to be off.

"Something to try: when in the program, if you activate the debug mode and hit & hold a key, then wait a second, then release, and then post what comes up in the console, that will give me a better idea of what type of inputs your piano is outputting into the program. And if you could explain how the program works otherwise, like does the keys to the avatar work?" 

Here's the debug for pressing and holding one key on the piano for about 5 seconds, then lifting the key again:
`pygame 2.5.0 (SDL 2.28.0, Python 3.11.4)
Hello from the pygame community. https://www.pygame.org/contribute.html
pygame-menu 4.4.3
Now listening to note events on <pygame.midi.Input object at 0x0000024281873050>...
here
PortStyle: 1
[[[144, 21, 85, 0], 10945]]
PortStyle: 1
[[[128, 21, 92, 0], 15535]]`

The avatar within VRChat uses the input of the LooBe signal perfectly fine. The keys on the avatar move, but they stay in their lowest position. This behaviour doesnt change, when dont use Synthesia but only OSC Midi and the avatar.

**Comment by brianops1** [comment]
Figured out what was going wrong, essentially your piano is sending the velocity for the off key as a higher than 0:
144, 21, 85, 0 -> note status (in midi CC), Key hit numerically, Velocity. I've just edited port 2 to use 144 as the on status and 128 as the off. _I've updated the file so just reinstall it and use port 2 and it should work_ let me know in here if it doesn't

**Comment by cer093** [comment]
Now it works like a charm, both in Synthesia and VRChat. Thanks a lot!
