### ISSUE TITLE
I created my own version of your program with new ui and more advanced code and simply had a few questions.

### ISSUE THREAD

**Issue by Mathieu52** [brianops1/OSCMidi#2]
Hey brianops1, so as the title states I've created my own version of OSCMidi originally inspired by yours. My version provides a more advanced UI along with visual clues. The goal of my version is also to make the installation process easier, by packaging the project into an exe file along with an installer.

### Information
- I confirm that your project works on Mac.
- I did not fork your project as my version is inspired by yours and should work similarly but is completely different when it comes to the code and packages used.
- I have yet to add a ReadMe to my project, waiting for your response first.
### Questions
- Is it okay if I recommend your avatars in my project?
- Do you want me to cite you?
- Do you want me to cite your project?
- Do you have any questions?
### Software Related Questions
- Is there a reason for the two different port styles?
	- After reading the Midi documentation, I only check for NoteOn and NoteOff events and do not consider a velocity of zero as a NoteOff event. I was wondering if I missed something that you haven't.
### Links to my project
- https://github.com/Mathieu52/OSCMidi

**Comment by brianops1** [comment]
Hello there Mat!

Firstly I'd like to say that I am glad I was able to inspire you to make something better! And as for your questions, yes, you can feel free to recommend my avatars. If I can login to the vrchat website I'll also make the best / newest avatar available because I haven't been working on it and I feel it deserves to be free. There is no need to cite me in anything unless you'd want to, but it is entirely your own work so I'd recommend not doing so. 

As for the Port Style... that is kind of a fossil left over from when I was testing different input types for different pianos. So you are not missing anything to take it out.

**Comment by brianops1** [comment]
Very sorry about the delay, but I finally got back into my account! The avatar is here: avtr_9afe6649-5eef-487d-84bf-237ac039d1ca

Though I hadn't finished it, it is better than the other two avatars in my opinion

**Comment by Mathieu52** [comment]
I don't mind the delay, I'll make sure to add your avatar to my project.
